include core team in alpha deployment

diff --git a/.github/workflows/alpha-deployment.yml b/.github/workflows/alpha-deployment.yml
--- a/.github/workflows/alpha-deployment.yml
+++ b/.github/workflows/alpha-deployment.yml
@@ -25,7 +25,7 @@ jobs:
             if [[ "${{ github.ref }}" =~ ^refs/heads/(release/|feature/) ]]; then
               echo "✅ Base branch ${{ github.ref }} is valid."
             else
-              echo "⛔ ERROR: Base branch ${ github.ref } is not valid. It should be release/ or feature/."
+              echo "⛔ ERROR: Base branch ${{ github.ref }} is not valid. It should be release/ or feature/."
               exit 1
             fi
 
@@ -37,7 +37,16 @@ jobs:
             if echo "$RESPONSE" | grep -q '"state": "active"'; then
               echo "✅ User ${{ github.actor }} is a member of the integration-developers team."
             else
-              echo "⛔ ERROR: User ${{ github.actor }} is not a member of the integration-developers team."
+              RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              -H "Accept: application/vnd.github.json" \
+              "https://api.github.com/orgs/utmstack/teams/core-developers/memberships/${{ github.actor }}")
+
+              if echo "$RESPONSE" | grep -q '"state": "active"'; then
+                echo "✅ User ${{ github.actor }} is a member of the core-developers team."
+              else
+                echo "⛔ ERROR: User ${{ github.actor }} is not a member of the core-developers or integration-developers team."
+              exit 1
+              fi
              exit 1
             fi
 
