update CI/CD pipelines

diff --git a/.github/workflows/rc-deployment.yml b/.github/workflows/rc-deployment.yml
--- a/.github/workflows/rc-deployment.yml
+++ b/.github/workflows/rc-deployment.yml
@@ -22,10 +22,10 @@ jobs:
           if [[ "${{ github.event.inputs.version_tag }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$ ]]; then
             echo "✅ Version tag format is correct."
 
-            if [[ "${ github.ref }" =~ ^refs/heads/main) ]]; then
-              echo "✅ Base branch ${ github.ref } is valid."
+            if [[ "${{ github.ref }}" =~ ^refs/heads/main) ]]; then
+              echo "✅ Base branch ${{ github.ref }} is valid."
             else
-              echo "⛔ ERROR: Base branch ${ github.ref } is not valid. It should be main."
+              echo "⛔ ERROR: Base branch ${{ github.ref }} is not valid. It should be main."
               exit 1
             fi
 
@@ -38,7 +38,7 @@ jobs:
               echo "✅ User ${{ github.actor }} is a member of the core-developers team."
             else
               echo "⛔ ERROR: User ${{ github.actor }} is not a member of the core-developers team."
-             exit 1
+              exit 1
             fi
 
           else
@@ -47,17 +47,16 @@ jobs:
           fi
 
   deploy:
-    name: Deploy
+    name: Deploy to RC
     needs: validations
     uses: ./.github/workflows/build.yml
     with:
       version_tag: ${{ github.event.inputs.version_tag }}
       event_processor_tag: ${{ github.event.inputs.event_processor_tag }}
       environment: rc
-      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
-      sign_cert: ${{ vars.SIGN_CERT }}
-      sign_key: ${{ secrets.SIGN_KEY }}
-      sign_container: ${{ secrets.SIGN_CONTAINER }}
-    env:
-      CM_AUTH: ${{ secrets.CM_AUTH_RC }}
+    secrets:
+      AGENT_SECRET_PREFIX: ${{ secrets.AGENT_SECRET_PREFIX }}
+      SIGN_KEY: ${{ secrets.SIGN_KEY }}
+      SIGN_CONTAINER: ${{ secrets.SIGN_CONTAINER }}
+      CM_AUTH: ${{ secrets.CM_AUTH_ALPHA }}
     
